config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

    resource :profile, only: [:show, :edit, :update]
    
    namespace :api, format: 'json' do
      resources :posts, only: [:index, :create, :show]
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  # has_one_attached :avatar
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  validates :account, presence: true, uniqueness: true
  validates :email, presence: true
  validates :encrypted_password, presence: true

  has_one :profile, dependent: :destroy
  has_many :posts, dependent: :destroy


  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default.jpeg'
    end
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  # before_action :authenticate_user!, only: [:create]

  def index
    @posts = Post.order('created_at DESC')
  end

  def create
    current_user = User.find(params[:user_id])
    @post = current_user.posts.new(post_params)
    if @post.save
      render :show, status: :created
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end
 
  private
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  # before_action :authenticate_user!, only: [:create]

  def index
    @posts = Post.order('created_at DESC')
  end

  def create
    current_user = User.find(params[:user_id])
    @post = current_user.posts.new(post_params)
    if @post.save
      render :show, status: :created
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end
 
  private
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:account])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def index
 end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  def show
    @profile = current_user.profile
  end

  def edit
  end

  def update
  end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h1 railsHome!!
= javascript_pack_tag 'hello_vue'
= link_to 'プロフィール', profile_path(current_user)
= button_to 'Exit', destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyPortfolio
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/profiles/edit.html.haml
= link_to "HOME", root_path
-# .container
-#   %ul
-#     - @profile.errors.full_messages.each do |message|
-#       %li= message
  
-#   = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
-#     %div
-#       = f.label :avatar, 'アバター'
-#     %div
-#       = f.file_field :avatar
-#     %div
-#       = f.label :nickname, 'ハンドルネーム'
-#     %div
-#       = f.text_field :nickname, class: 'text'
-#     %div
-#       = f.label :introduction, '自己紹介'
-#     %div
-#       = f.text_area :introduction
-#     %div
-#       = f.label :gender, '性別'
-#     %div
-#       = f.select :gender, Profile.genders.map { |k, v| [ I18n.t("enum.genders.#{k}"), k ] }, {}, { class: 'text' }
-#     %div
-#       = f.label :birthday, '生年月日'
-#     %div
-#       = f.date_field :birthday, class: 'text'
-#     %div
-#       = f.label :subscribed, '通知を受け取る'
-#       = f.check_box :subscribed
    
-#     = f.submit '保存', class: 'btn-primary'  
      
      

app/views/profiles/show.html.haml
-# = javascript_pack_tag 'hello_vue'
%h1 railsのプロフィールページ
= current_user.id
= current_user.email
= current_user.account
= link_to 'edit page', edit_profile_path(current_user)
.container.profilePage
  .profilePage_user
    .profilePage_user_image
  -#     = image_tag user.avatar_image
  -#   .profilePage_user_basicInfo
  -#     .profilePage_user_name
  -#       .profilePage_user_displayName
  -#         #{user.display_name} 
  -#       .profilePage_user_actionButton
  -#         - if user == current_user
  -#           = link_to 'Edit', edit_profile_path
  -#         - else 
  -#           - if current_user&.has_followed?(user)
  -#             = link_to 'Unfollow', account_unfollows_path(user), data: { method: 'post' }
  -#           - else  
  -#             = link_to 'Follow', account_follows_path(user), data: { method: 'post' }
  -#     .profilePage_user_introduction
  -#       = user.profile&.introduction

  -# - user.articles.each do |article|
    -# = render 'commons/article', article: article

    

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/